# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

config.vm.define "manager1" do |manager1|
    manager1.vm.hostname = "manager1"
    manager1.vm.box = "ubuntu1604"
    manager1.vm.network :private_network, ip: "192.168.33.101"
#    manager1.vm.synced_folder "./", "/vagrant"
end

config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.box = "ubuntu1604"
    worker1.vm.network :private_network, ip: "192.168.33.102"
end

# OSS Guest
 config.vm.define "worker2" do |worker2|
   worker2.vm.hostname = "worker2"
   worker2.vm.box = "ubuntu1604"
   worker2.vm.network :private_network, ip: "192.168.33.103"

 end
end
