# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

config.vm.define "syslog01" do |syslog01|
    syslog01.vm.hostname = "syslog01"
    syslog01.vm.box = "ubuntu/precise64"
    syslog01.vm.network :private_network, ip: "192.168.33.101"
end

config.vm.define "client01" do |client01|
    client01.vm.hostname = "client01"
    client01.vm.box = "ubuntu/trusty64"
    client01.vm.network :private_network, ip: "192.168.33.102"

#clients 102 - 109 only

end
 end
