# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.box = "precise64"
    server.vm.network :private_network, ip: "192.168.33.200"
end

config.vm.define "oss" do |oss|
    oss.vm.hostname = "client"
    oss.vm.box = "ubuntu/trusty64"
    oss.vm.network :private_network, ip: "192.168.33.201"
end
#
# # OSS Guest
# config.vm.define "oss" do |oss|
#   oss.vm.hostname = "oss"
#   oss.vm.box = "ubuntu/trusty64"
#   oss.vm.network :private_network, ip: "192.168.10.6"
 end
